from django.urls import path

from . import views

urlpatterns = [
    path("health", views.health, name="health"),
    path("migration-status", views.migration_status, name="migration-status"),
    path("booking-link", views.booking_link, name="booking-link"),
    path("teams-call-context", views.teams_call_context, name="teams-call-context"),
    path("verify-email", views.verify_email, name="verify-email"),
    path("admin/login", views.admin_login, name="admin-login"),
    path("admin/logout", views.admin_logout, name="admin-logout"),
    path("admin/session-heartbeat", views.admin_session_heartbeat, name="admin-session-heartbeat"),
    path("admin/accounts", views.admin_accounts, name="admin-accounts"),
    path("admin/accounts/<int:agent_id>", views.admin_account_detail, name="admin-account-detail"),
    path("admin/agents", views.admin_accounts, name="admin-agents"),
    path("admin/agents/<int:agent_id>", views.admin_account_detail, name="admin-agent-detail"),
    path("admin/tickets", views.admin_tickets, name="admin-tickets"),
    path("admin/notifications", views.admin_notifications, name="admin-notifications"),
    path("admin/tickets/<str:public_id>/ai-agent-message", views.admin_ticket_ai_message, name="admin-ticket-ai-message"),
    path("admin/tickets/<str:public_id>/follow-up-ticket", views.admin_ticket_follow_up, name="admin-ticket-follow-up"),
    path("admin/tickets/<str:public_id>/transfer-request", views.admin_ticket_transfer_request, name="admin-ticket-transfer-request"),
    path("admin/tickets/<str:public_id>/transfer-request/accept", views.admin_ticket_transfer_request_accept, name="admin-ticket-transfer-request-accept"),
    path("admin/tickets/<str:public_id>/transfer-request/reject", views.admin_ticket_transfer_request_reject, name="admin-ticket-transfer-request-reject"),
    path("admin/tickets/<str:public_id>/transfer-decision/acknowledge", views.admin_ticket_transfer_decision_acknowledge, name="admin-ticket-transfer-decision-acknowledge"),
    path("admin/tickets/<str:public_id>/teams-call-notification/acknowledge", views.admin_ticket_teams_call_notification_acknowledge, name="admin-ticket-teams-call-notification-acknowledge"),
    path("admin/tickets/<str:public_id>/escalation-notification/acknowledge", views.admin_ticket_escalation_notification_acknowledge, name="admin-ticket-escalation-notification-acknowledge"),
    path("admin/tickets/<str:public_id>/escalation-closure/acknowledge", views.admin_ticket_escalation_closure_acknowledge, name="admin-ticket-escalation-closure-acknowledge"),
    path("admin/tickets/<str:public_id>", views.admin_ticket_detail, name="admin-ticket-detail"),
    path("tickets", views.tickets_create, name="tickets-create"),
    path("tickets/<str:public_id>", views.tickets_update, name="tickets-update"),
    path("tickets/<str:public_id>/chat-history", views.ticket_chat_history, name="ticket-chat-history"),
    path("tickets/<str:public_id>/chatbot-message", views.ticket_chatbot_message, name="ticket-chatbot-message"),
    path("tickets/<str:public_id>/live-chat-request", views.ticket_live_chat_request, name="ticket-live-chat-request"),
    path("tickets/<str:public_id>/teams-call-request", views.ticket_teams_call_request, name="ticket-teams-call-request"),
    path("tickets/<str:public_id>/chat-context", views.ticket_chat_context, name="ticket-chat-context"),
    path("tickets/<str:public_id>/booking-context", views.ticket_booking_context, name="ticket-booking-context"),
    path("tickets/<str:public_id>/session-requests", views.ticket_session_request, name="ticket-session-request"),
    path("tickets/<str:public_id>/session-requests/cancel", views.ticket_session_request_cancel, name="ticket-session-request-cancel"),
]
